### ISSUE TITLE
Issue: se podrán integrar ambas ramas?

### ISSUE THREAD

**Issue by emilio-molina** [salasgar/Ecosystems#2]
pues eso se podrán integrar Nacimiento y muerte y la nueva rama? Si no es así, y estás integrando todo en la nueva rama, mejor eliminar Nacimiento y muerte para no liarnos.

p.d.: los issues son para notificar cosas que no funcionan o que son un issue, y luego se pueden cerrar cuando ya estén resueltos.

**Comment by salasgar** [comment]
Ok. Acabo de ver el issue. No sabía que existían los issues. Estaré pendiente de ello.
