### ISSUE TITLE
spread speed of a substance

### ISSUE THREAD

**Issue by salasgar** [salasgar/Ecosystems#5]
Una sustancia suele moverse de las zonas donde su concentración es mayor hacia las zonas donde su concentración es menor. Pero la velocidad a la que se extiende y su manera de extenderse cambia de una substancia a otra. 
Cada cierto número N de ciclos, la distribución de esa sustancia cambia. Cada punto toma el valor de la media aritmética de los puntos que están a distancia menor o igual que D.

Mi problema qué nombre ponerle a esas variables N y D. A la N le he puesto 'spread_frequency', aunque en realidad es la inversa de la frecuencia. Y a la D la he llamado 'spread_speed', que tampoco sé si es el nombre más adecuado.

Yo llamo 'substance' a cualquier cosa del biotopo que se pueda representar como una función que asigna un valor real a cada punto del biotopo. En esto incluyo:
Altitud  
Temperatura
Cantidad de luz solar que incide en la superficie
Profundidad del agua (en tierra firme la profundidad es 0)
Humedad (en los ríos y lagos la humedad es del 100%)
etc...

La distribución de unas sustancias puede afectar a otras. Por ejemplo:
 La altitud puede afectar a la temperatura, a la cantidad de lluvia, al desplazamiento del agua (es decir, a la sustancia DEPTH), etc...
A su vez, el desplazamiento del agua genera erosión, que modifica la variable Altitud.

**Comment by emilio-molina** [comment]
Todo esto está ya implementado? A ver si conseguimos que no complique el código demasiado y que yo lo pueda entender luego

**Comment by salasgar** [comment]
Hola. No he tenido tiempo estos días para seguir implementando. No te molestes en leer lo que hay, porque he pensado hacerlo de otra manera para que quede más legible.
Te propongo lo siguiente:

Vamos a definir un experimento que queramos hacer y entonces implementamos solamente lo necesario para llevarlo a cabo. Es decir: imagínate un ecosistema que quieras probar. Por ejemplo, una cosa sencilla sería definir una especie de animal, otra de planta y ver qué proporción de organismos son plantas y qué proporción de organismos son animales. Podemos ver bajo qué condiciones el ecosistema que sale es más estable y bajo qué condiciones es más oscilante, en cuanto al número de individuos de cada especie. Luego veríamos si al introducir una especie de carnívoros, que solo coman animales, el ecosistema se hace más estable (yo creo que sí).

Así, por ejemplo, no tendríamos que introducir mutaciones en la reproducción, por ejemplo.

Una vez que hayamos probado y frikeado con un experimento, podemos ir a por otro. Y así siempre tenemos algo terminado que funciona y que mola. ¿Te parece bien? Es que si no nos vamos a perder en un vasto océano de posibilidades. Por ejemplo, yo he estado haciendo lo de las sustancias pensando en que en algún momento las coordenadas de los organismos puedan ser números reales no enteros y a lo mejor debería descartar de momento esa posibilidad para no complicar el código. Mi idea era que pudiéramos modelar los organismos como esferas o círculos, con un centro y un radio. En función de su área o su volumen podrían almacenar más sustancias de reserva o menos. O bien su volumen podría venir dado por la cantidad de sustancias que tuvieran, o su capacidad fotosintética podría depender de su superficie. Al ser coordenadas reales, podría haber organismos que se desplazaran muy despacio. Podría haber algunos que se especializaran en ser pequeños y poderse mover por los huecos que dejen los grandes, etc.... Pero da igual. Lo descartamos.

**Comment by emilio-molina** [comment]
Me parece guay la idea de tener experimentos que funcionan, y puede servir para ir siendo consciente de las estructuras de datos que mejor nos van.

Podemos entonces crear carpetas en el repositorio llamadas Experimento1, Experimento2... y vamos duplicando los ficheros. Así dentro de cada carpeta se puede ejecutar el main y todo debe funcionar.

La parte mala es la duplicación de código, que es algo que suele dar trabajo innecesario por un mal diseño inicial. Por lo tanto, mi propuesta es seguir esta metodología mediante experimentos, pero intentar ir buscando un diseño conjunto que sirva para todo.

**Comment by emilio-molina** [comment]
Por otro lado, yo no intentaría hacer todo muy eficiente desde el principio, sino hacerlo simple y posteriormente podemos ir haciendo profiling para ir encontrando los cuellos de botella. Quizá lo que más nos limita no sea lo que nos esperamos :)

**Comment by emilio-molina** [comment]
Por cierto. ¿qué es Substance of degree0... degree1?

**Comment by salasgar** [comment]
Lo siento. Hoy tampoco he tenido tiempo para ponerme con esto. Intentaré sacar un hueco mañana.

Una sustancia se puede modelar como una aplicación que asigna a cada punto del biotopo un valor real positivo, que representará la concentración de esa sustancia en ese punto. Pero el biotopo tiene muchos puntos, y no es eficiente almacenar un valor distinto para cada punto del biotopo, de manera que almacenamos menos valores y estimamos el valor de los demás puntos a partir de esos, mediante una función de interpolación que puede ser de grado 0, de grado 1, etc... eso es el degree.
