### ISSUE TITLE
Substance resolution

### ISSUE THREAD

**Issue by salasgar** [salasgar/Ecosystems#6]
Hay sustancias que no requieren un nivel de precisión milimétrico. Por ejemplo, la temperatura que hay en un punto del biotopo suele ser muy parecida a la que hay a su alrededor. Si "pixelamos" la distribución de la temperatura y almacenamos menos datos ahorraremos tiempo de computación cuando tengamos que ir actualizando esa distribución tras cada iteración (o cada N iteraciones).

No sé si llamarle 'substance_resolution', en cuyo caso, si queremos guardar un dato por cada cuadrado 3x3 del biotopo habría que poner:  

substance.resolution_x = BIOTOPE_SIZE_X / 3
substance.resolution_y = BIOTOPE_SIZE_Y / 3

O bien ponerle otro nombre, como 'block_size' o algo así, y pondríamos:

substance.block_size_x = 3
substance.block_size_y = 3

O simplemente:

substance.block_size = 3

**Comment by emilio-molina** [comment]
Ok. Lo único malo es que complica el código, no?

**Comment by salasgar** [comment]
Bueno, vamos a dejar de momento lo del block_size y si luego vemos que estorba mucho, se quita. ok?
